### ISSUE TITLE
wordpress.org

### ISSUE THREAD

**Issue by olijens** [birgire/wp-default-author#3]
Make the plugin available at wordpress.org

**Comment by birgire** [comment]
We will need a 772x250 banner image for that ;-)

Here is for example the Akismet banner:

http://s-plugins.wordpress.org/akismet/assets/banner-772x250.jpg?rev=479904

**Comment by olijens** [comment]
http://wordpress.org/plugins/wp-super-cache/ this one doesnt seem to have a banner.

**Comment by birgire** [comment]
oh no, that's so boring ;-)

**Comment by birgire** [comment]
Here we go

http://wordpress.org/plugins/wp-default-author/

**Comment by cliffordp** [comment]
Excellent! I suggest addressing the eventual question, "Will this work on multisite?" At least saying it must be set per site and doesn't have any network-level settings would be good. Committing to putting it on the to-do list is another issue.
